#!/bin/sh

CLASSPATH="./libs/commons-codec-1.9.jar"
CLASSPATH="$CLASSPATH:./libs/commons-io-2.5.jar"
CLASSPATH="$CLASSPATH:./libs/commons-lang3-3.4.jar"
CLASSPATH="$CLASSPATH:./libs/jcl-over-slf4j-1.7.13.jar"
CLASSPATH="$CLASSPATH:./libs/logback-classic-1.1.3.jar"
CLASSPATH="$CLASSPATH:./libs/logback-core-1.1.3.jar"
CLASSPATH="$CLASSPATH:./libs/slf4j-api-1.7.13.jar"
CLASSPATH="$CLASSPATH:./libs/support-common-util-1.0.0.0-SNAPSHOT.jar"

if [ ! -z "$JAVA_HOME" ]; then
	EXECUTOR="$JAVA_HOME/bin/java"
else
	EXECUTOR="java"
fi

MAINCLASS="com.lachesis.support.common.util.crypt.bootstrap.PasswordCryptTool"

$EXECUTOR -cp $CLASSPATH $MAINCLASS $@