USE [master]
GO

/****** Object:  Database [USP]    Script Date: 11/24/2016 10:50:46 ******/
CREATE DATABASE [USP] ON  PRIMARY 
( NAME = N'USP', FILENAME = N'D:\Program Files\Microsoft SQL Server\MSSQL10_50.MSSQLSERVER\MSSQL\DATA\USP.mdf' , SIZE = 3072KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'USP_log', FILENAME = N'D:\Program Files\Microsoft SQL Server\MSSQL10_50.MSSQLSERVER\MSSQL\DATA\USP_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [USP] SET COMPATIBILITY_LEVEL = 100
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [USP].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [USP] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [USP] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [USP] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [USP] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [USP] SET ARITHABORT OFF 
GO

ALTER DATABASE [USP] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [USP] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [USP] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [USP] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [USP] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [USP] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [USP] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [USP] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [USP] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [USP] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [USP] SET  DISABLE_BROKER 
GO

ALTER DATABASE [USP] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [USP] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [USP] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [USP] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [USP] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [USP] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [USP] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [USP] SET  READ_WRITE 
GO

ALTER DATABASE [USP] SET RECOVERY FULL 
GO

ALTER DATABASE [USP] SET  MULTI_USER 
GO

ALTER DATABASE [USP] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [USP] SET DB_CHAINING OFF 
GO

