USE [USP]
GO

/****** Object:  Table [dbo].[R_ROLE_PERMISSION]    Script Date: 11/23/2016 10:20:12 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[R_ROLE_PERMISSION](
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[ROLE_ID] [bigint] NOT NULL,
	[PERMISSION_ID] [bigint] NOT NULL,
	[IS_DELETED] [char](1) NULL,
	[CREATE_AT] [datetime] NULL,
	[UPDATE_AT] [datetime] NULL,
	[CREATE_BY_USER_ID] [bigint] NULL,
	[UPDATE_BY_USER_ID] [bigint] NULL,
	[DATA_SOURCE] [varchar](50) NULL,
 CONSTRAINT [PK_R_ROLE_PERMISSION] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[R_ROLE_PERMISSION] ADD  CONSTRAINT [DF_R_ROLE_PERMISSION_IS_DELETED]  DEFAULT ('N') FOR [IS_DELETED]
GO

