USE [USP]
GO

/****** Object:  Table [dbo].[T_USER]    Script Date: 11/23/2016 10:18:07 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[T_USER](
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[CODE] [varchar](20) NULL,
	[USERNAME] [varchar](50) NULL,
	[PASSWORD] [varchar](100) NULL,
	[NAME] [varchar](50) NULL,
	[GENDER] [char](10) NULL,
	[MOBILE_PHONE] [varchar](50) NULL,
	[TELEPHONE] [varchar](50) NULL,
	[EMAIL] [varchar](50) NULL,
	[IS_ACTIVE] [char](1) NULL,
	[IS_LOCKED] [char](1) NULL,
	[IS_DELETED] [char](1) NULL,
	[CREATE_AT] [datetime] NULL,
	[UPDATE_AT] [datetime] NULL,
	[CREATE_BY_USER_ID] [bigint] NULL,
	[UPDATE_BY_USER_ID] [bigint] NULL,
	[DATA_SOURCE] [varchar](20) NULL,
 CONSTRAINT [PK_USER] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[T_USER] ADD  CONSTRAINT [DF_USER_IS_ACTIVE]  DEFAULT ('Y') FOR [IS_ACTIVE]
GO

ALTER TABLE [dbo].[T_USER] ADD  CONSTRAINT [DF_USER_IS_LOCKED]  DEFAULT ('N') FOR [IS_LOCKED]
GO

ALTER TABLE [dbo].[T_USER] ADD  CONSTRAINT [DF_USER_IS_DELETED]  DEFAULT ('N') FOR [IS_DELETED]
GO

