USE [USP]
GO

/****** Object:  Table [dbo].[T_PERMISSION]    Script Date: 11/23/2016 10:19:20 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[T_PERMISSION](
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[CODE] [varchar](50) NULL,
	[NAME] [varchar](50) NULL,
	[LABEL] [nvarchar](50) NULL,
	[DESCRIPTION] [nvarchar](50) NULL,
	[IS_DELETED] [char](1) NULL,
 CONSTRAINT [PK_PERMISSION] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[T_PERMISSION] ADD  CONSTRAINT [DF_PERMISSION_IS_DELETED]  DEFAULT ('N') FOR [IS_DELETED]
GO

